import { useState } from "react";
import { ToolLayout } from "@/components/ToolLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Copy, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const RobotsTxt = () => {
  const [sitemap, setSitemap] = useState("");
  const [allowAll, setAllowAll] = useState(false);
  const [disallowAll, setDisallowAll] = useState(false);
  const [customRules, setCustomRules] = useState("");
  const [result, setResult] = useState("");
  const { toast } = useToast();

  const generateRobotsTxt = () => {
    let robots = "# robots.txt generated by DevToolkit\n\n";
    
    robots += "User-agent: *\n";
    
    if (allowAll) {
      robots += "Allow: /\n";
    } else if (disallowAll) {
      robots += "Disallow: /\n";
    } else if (customRules) {
      robots += customRules + "\n";
    } else {
      robots += "Disallow: /admin/\nDisallow: /private/\n";
    }
    
    if (sitemap) {
      robots += `\nSitemap: ${sitemap}\n`;
    }

    setResult(robots);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(result);
    toast({
      title: "Copied!",
      description: "Robots.txt copied to clipboard",
    });
  };

  return (
    <ToolLayout
      title="Robots.txt Generator"
      description="Generate robots.txt file for your website"
    >
      <Card className="p-6 space-y-4">
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="sitemap">Sitemap URL (optional)</Label>
            <Input
              id="sitemap"
              value={sitemap}
              onChange={(e) => setSitemap(e.target.value)}
              placeholder="https://example.com/sitemap.xml"
            />
          </div>

          <div className="flex items-center space-x-2">
            <Checkbox
              id="allow-all"
              checked={allowAll}
              onCheckedChange={(checked) => {
                setAllowAll(checked as boolean);
                if (checked) setDisallowAll(false);
              }}
            />
            <Label htmlFor="allow-all">Allow all crawlers</Label>
          </div>

          <div className="flex items-center space-x-2">
            <Checkbox
              id="disallow-all"
              checked={disallowAll}
              onCheckedChange={(checked) => {
                setDisallowAll(checked as boolean);
                if (checked) setAllowAll(false);
              }}
            />
            <Label htmlFor="disallow-all">Disallow all crawlers</Label>
          </div>

          <div className="space-y-2">
            <Label htmlFor="custom">Custom Rules</Label>
            <Textarea
              id="custom"
              value={customRules}
              onChange={(e) => setCustomRules(e.target.value)}
              placeholder="Disallow: /admin/&#10;Disallow: /private/"
              rows={4}
            />
          </div>

          <Button onClick={generateRobotsTxt}>
            <FileText className="mr-2 h-4 w-4" />
            Generate Robots.txt
          </Button>

          {result && (
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <Label>Generated Robots.txt</Label>
                <Button size="sm" variant="outline" onClick={copyToClipboard}>
                  <Copy className="mr-2 h-4 w-4" />
                  Copy
                </Button>
              </div>
              <Textarea value={result} readOnly rows={10} />
            </div>
          )}
        </div>
      </Card>
    </ToolLayout>
  );
};

export default RobotsTxt;
